name: QA
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install poetry
        run: python -m pip install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Python packages
        run: poetry install --with dev

      - name: Run QA scripts
        run: ./scripts/qa.sh

      - name: Test Docker Build
        run: ./scripts/docker-build.sh
